//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a4fd25_pppEntities1 : DbContext
    {
        public db_a4fd25_pppEntities1()
            : base("name=db_a4fd25_pppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_clientep> tb_clientep { get; set; }
        public virtual DbSet<tb_codigop> tb_codigop { get; set; }
        public virtual DbSet<tb_despesap> tb_despesap { get; set; }
        public virtual DbSet<tb_estoquep> tb_estoquep { get; set; }
        public virtual DbSet<tb_folhapagamentop> tb_folhapagamentop { get; set; }
        public virtual DbSet<tb_fornecedorp> tb_fornecedorp { get; set; }
        public virtual DbSet<tb_funcionariosp> tb_funcionariosp { get; set; }
        public virtual DbSet<tb_loginp> tb_loginp { get; set; }
        public virtual DbSet<tb_pedido_clientep> tb_pedido_clientep { get; set; }
        public virtual DbSet<tb_produtop> tb_produtop { get; set; }
        public virtual DbSet<tb_venda_clientep> tb_venda_clientep { get; set; }
    }
}
