//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compras_cliente
    {
        public int id_compra { get; set; }
        public Nullable<System.DateTime> dt_compra { get; set; }
        public Nullable<decimal> vl_compra { get; set; }
        public string nm_produto_estoque { get; set; }
        public Nullable<int> id_cliente_produto { get; set; }
    }
}
