//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_pedido_cliente = new HashSet<tb_pedido_cliente>();
            this.tb_venda_cliente = new HashSet<tb_venda_cliente>();
        }
    
        public int id_cliente { get; set; }
        public string nm_nome { get; set; }
        public string end_endereco { get; set; }
        public string doc_rg { get; set; }
        public string doc_cep { get; set; }
        public string pes_email { get; set; }
        public string tel_telefone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_cliente> tb_pedido_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_venda_cliente> tb_venda_cliente { get; set; }
    }
}
