//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_clientes
    {
        public int id_clientes { get; set; }
        public string nm_nome { get; set; }
        public string end_endereco { get; set; }
        public string doc_rg { get; set; }
        public string doc_cep { get; set; }
        public string pes_email { get; set; }
        public string tel_telefone { get; set; }
    }
}
