//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_despesas
    {
        public int id_despesas { get; set; }
        public Nullable<decimal> vl_valor { get; set; }
        public Nullable<System.DateTime> dt_data { get; set; }
        public string tp_conta { get; set; }
    }
}
