//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedorp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_fornecedorp()
        {
            this.tb_estoquep = new HashSet<tb_estoquep>();
            this.tb_produtop = new HashSet<tb_produtop>();
        }
    
        public int id_fornecedor { get; set; }
        public string nm_produto { get; set; }
        public string nm_fornecedor { get; set; }
        public string end_endereço { get; set; }
        public string tl_telefone { get; set; }
        public string fr_cep { get; set; }
        public string fr_cnpj { get; set; }
        public Nullable<decimal> vl_valor_produto { get; set; }
        public Nullable<System.DateTime> dt_entrada_do_produto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoquep> tb_estoquep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_produtop> tb_produtop { get; set; }
    }
}
