//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_folhapagamento
    {
        public int id_folha_pagamento { get; set; }
        public Nullable<decimal> ds_inss { get; set; }
        public Nullable<decimal> hora_extra { get; set; }
        public Nullable<decimal> ad_gratificação { get; set; }
        public Nullable<decimal> imposto_renda { get; set; }
        public Nullable<decimal> vl_alimentação { get; set; }
        public Nullable<decimal> vl_transporte { get; set; }
        public Nullable<int> ds_faltas { get; set; }
        public Nullable<decimal> sl_salario_liquido { get; set; }
        public string nm_funcionario { get; set; }
        public Nullable<decimal> sl_salario_bruto { get; set; }
        public Nullable<System.DateTime> dt_pagamento { get; set; }
    }
}
