//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_funcionario()
        {
            this.tb_folhapagamento = new HashSet<tb_folhapagamento>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_dependentes { get; set; }
        public string nm_responsavel { get; set; }
        public string nm_funcionario { get; set; }
        public string fc_telefone { get; set; }
        public string fc_telefone_emergencia { get; set; }
        public int dp_idade { get; set; }
        public System.DateTime dt_nasc { get; set; }
        public string fc_rg { get; set; }
        public string fc_cpf { get; set; }
        public string fc_endereço { get; set; }
        public string fc_cargo { get; set; }
        public System.DateTime dt_data_de_contratacao { get; set; }
        public Nullable<System.DateTime> dt_pagamento { get; set; }
        public decimal sl_salario_familia { get; set; }
        public decimal sl_salario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_folhapagamento> tb_folhapagamento { get; set; }
    }
}
