//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_fornecedor()
        {
            this.tb_compra = new HashSet<tb_compra>();
            this.tb_estoque = new HashSet<tb_estoque>();
            this.tb_produto = new HashSet<tb_produto>();
        }
    
        public int id_fornecedor { get; set; }
        public string nm_razao_social { get; set; }
        public string nm_fantasia { get; set; }
        public string nm_produto { get; set; }
        public string nm_fornecedor { get; set; }
        public string end_endereço { get; set; }
        public string tl_telefone { get; set; }
        public string fr_cep { get; set; }
        public string fr_cnpj { get; set; }
        public Nullable<decimal> vl_valor_produto { get; set; }
        public Nullable<System.DateTime> dt_entrada_do_produto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_compra> tb_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_produto> tb_produto { get; set; }
    }
}
