//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionarios
    {
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public Nullable<System.DateTime> dt_nasc { get; set; }
        public Nullable<int> fun_rg { get; set; }
        public Nullable<int> fun_cpf { get; set; }
        public string fun_endereço { get; set; }
        public Nullable<decimal> ad_fgts { get; set; }
        public Nullable<decimal> sl_salario { get; set; }
        public Nullable<System.DateTime> dt_data_de_contratacao { get; set; }
        public string fun_cargo { get; set; }
    }
}
