//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        public int id_produto { get; set; }
        public string nm_fornecedor_produto { get; set; }
        public string nm_produto { get; set; }
        public string cat_categoria { get; set; }
        public string sb_sabor { get; set; }
    }
}
