//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_cliente
    {
        public int id_pedido { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string nm_nome { get; set; }
        public Nullable<int> qtd_quantidade { get; set; }
        public Nullable<int> id_produto { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_produto tb_produto { get; set; }
    }
}
