//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERIADO_JARVIS_.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produtop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_produtop()
        {
            this.tb_pedido_clientep = new HashSet<tb_pedido_clientep>();
            this.tb_venda_clientep = new HashSet<tb_venda_clientep>();
        }
    
        public int id_produto { get; set; }
        public string nm_fornecedor_produto { get; set; }
        public string nm_produto { get; set; }
        public string cat_categoria { get; set; }
        public string sb_sabor { get; set; }
        public Nullable<int> id_fornecedor { get; set; }
    
        public virtual tb_fornecedorp tb_fornecedorp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_clientep> tb_pedido_clientep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_venda_clientep> tb_venda_clientep { get; set; }
    }
}
